/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** the whole estate's current status */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description one snapshot of the registry, stamped when it was rendered */
        status: {
            /**
             * Format: date-time
             * @description when the daemon rendered this document
             */
            generated: string;
            rollup: components["schemas"]["rollup"];
            /** @description every check in registry order; sorting is a render decision */
            checks: components["schemas"]["check"][];
        };
        /** @description how many checks occupy each state */
        rollup: {
            ok: number;
            late: number;
            failed: number;
        };
        check: {
            /** @description the registry slug, also the report path segment */
            id: string;
            /** @description the display name */
            name: string;
            kind: components["schemas"]["kind"];
            state: components["schemas"]["state"];
            /**
             * Format: date-time
             * @description when the check entered its current state
             */
            since: string;
            /**
             * Format: date-time
             * @description null until the check's first real transition; registration is not one
             */
            last_transition: string | null;
            /**
             * Format: date-time
             * @description the last passive report; null for active checks
             */
            last_seen: string | null;
            /** @description detail from the last result or report; null until one arrives */
            detail: string | null;
        };
        /**
         * @description how the check receives results
         * @enum {string}
         */
        kind: "passive" | "http" | "tcp";
        /**
         * @description the damped runtime verdict
         * @enum {string}
         */
        state: "ok" | "late" | "failed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description every registered check with its current state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["status"];
                };
            };
        };
    };
}
