// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/check
type Check struct {
	// The registry slug, also the report path segment.
	ID string `json:"id"`
	// The display name.
	Name  string `json:"name"`
	Kind  Kind   `json:"kind"`
	State State  `json:"state"`
	// When the check entered its current state.
	Since time.Time `json:"since"`
	// Null until the check's first real transition; registration is not one.
	LastTransition NilDateTime `json:"last_transition"`
	// The last passive report; null for active checks.
	LastSeen NilDateTime `json:"last_seen"`
	// Detail from the last result or report; null until one arrives.
	Detail NilString `json:"detail"`
}

// GetID returns the value of ID.
func (s *Check) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Check) GetName() string {
	return s.Name
}

// GetKind returns the value of Kind.
func (s *Check) GetKind() Kind {
	return s.Kind
}

// GetState returns the value of State.
func (s *Check) GetState() State {
	return s.State
}

// GetSince returns the value of Since.
func (s *Check) GetSince() time.Time {
	return s.Since
}

// GetLastTransition returns the value of LastTransition.
func (s *Check) GetLastTransition() NilDateTime {
	return s.LastTransition
}

// GetLastSeen returns the value of LastSeen.
func (s *Check) GetLastSeen() NilDateTime {
	return s.LastSeen
}

// GetDetail returns the value of Detail.
func (s *Check) GetDetail() NilString {
	return s.Detail
}

// SetID sets the value of ID.
func (s *Check) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Check) SetName(val string) {
	s.Name = val
}

// SetKind sets the value of Kind.
func (s *Check) SetKind(val Kind) {
	s.Kind = val
}

// SetState sets the value of State.
func (s *Check) SetState(val State) {
	s.State = val
}

// SetSince sets the value of Since.
func (s *Check) SetSince(val time.Time) {
	s.Since = val
}

// SetLastTransition sets the value of LastTransition.
func (s *Check) SetLastTransition(val NilDateTime) {
	s.LastTransition = val
}

// SetLastSeen sets the value of LastSeen.
func (s *Check) SetLastSeen(val NilDateTime) {
	s.LastSeen = val
}

// SetDetail sets the value of Detail.
func (s *Check) SetDetail(val NilString) {
	s.Detail = val
}

// How the check receives results.
// Ref: #/components/schemas/kind
type Kind string

const (
	KindPassive Kind = "passive"
	KindHTTP    Kind = "http"
	KindTCP     Kind = "tcp"
)

// AllValues returns all Kind values.
func (Kind) AllValues() []Kind {
	return []Kind{
		KindPassive,
		KindHTTP,
		KindTCP,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Kind) MarshalText() ([]byte, error) {
	switch s {
	case KindPassive:
		return []byte(s), nil
	case KindHTTP:
		return []byte(s), nil
	case KindTCP:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Kind) UnmarshalText(data []byte) error {
	switch Kind(data) {
	case KindPassive:
		*s = KindPassive
		return nil
	case KindHTTP:
		*s = KindHTTP
		return nil
	case KindTCP:
		*s = KindTCP
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewNilDateTime returns new NilDateTime with value set to v.
func NewNilDateTime(v time.Time) NilDateTime {
	return NilDateTime{
		Value: v,
	}
}

// NilDateTime is nullable time.Time.
type NilDateTime struct {
	Value time.Time
	Null  bool
}

// SetTo sets value to v.
func (o *NilDateTime) SetTo(v time.Time) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilDateTime) SetToNull() {
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// How many checks occupy each state.
// Ref: #/components/schemas/rollup
type Rollup struct {
	Ok     int `json:"ok"`
	Late   int `json:"late"`
	Failed int `json:"failed"`
}

// GetOk returns the value of Ok.
func (s *Rollup) GetOk() int {
	return s.Ok
}

// GetLate returns the value of Late.
func (s *Rollup) GetLate() int {
	return s.Late
}

// GetFailed returns the value of Failed.
func (s *Rollup) GetFailed() int {
	return s.Failed
}

// SetOk sets the value of Ok.
func (s *Rollup) SetOk(val int) {
	s.Ok = val
}

// SetLate sets the value of Late.
func (s *Rollup) SetLate(val int) {
	s.Late = val
}

// SetFailed sets the value of Failed.
func (s *Rollup) SetFailed(val int) {
	s.Failed = val
}

// The damped runtime verdict.
// Ref: #/components/schemas/state
type State string

const (
	StateOk     State = "ok"
	StateLate   State = "late"
	StateFailed State = "failed"
)

// AllValues returns all State values.
func (State) AllValues() []State {
	return []State{
		StateOk,
		StateLate,
		StateFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s State) MarshalText() ([]byte, error) {
	switch s {
	case StateOk:
		return []byte(s), nil
	case StateLate:
		return []byte(s), nil
	case StateFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *State) UnmarshalText(data []byte) error {
	switch State(data) {
	case StateOk:
		*s = StateOk
		return nil
	case StateLate:
		*s = StateLate
		return nil
	case StateFailed:
		*s = StateFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// One snapshot of the registry, stamped when it was rendered.
// Ref: #/components/schemas/status
type Status struct {
	// The display name of the monitored estate.
	Estate string `json:"estate"`
	// When the daemon rendered this document.
	Generated time.Time `json:"generated"`
	Rollup    Rollup    `json:"rollup"`
	// Every check in registry order; sorting is a render decision.
	Checks []Check `json:"checks"`
}

// GetEstate returns the value of Estate.
func (s *Status) GetEstate() string {
	return s.Estate
}

// GetGenerated returns the value of Generated.
func (s *Status) GetGenerated() time.Time {
	return s.Generated
}

// GetRollup returns the value of Rollup.
func (s *Status) GetRollup() Rollup {
	return s.Rollup
}

// GetChecks returns the value of Checks.
func (s *Status) GetChecks() []Check {
	return s.Checks
}

// SetEstate sets the value of Estate.
func (s *Status) SetEstate(val string) {
	s.Estate = val
}

// SetGenerated sets the value of Generated.
func (s *Status) SetGenerated(val time.Time) {
	s.Generated = val
}

// SetRollup sets the value of Rollup.
func (s *Status) SetRollup(val Rollup) {
	s.Rollup = val
}

// SetChecks sets the value of Checks.
func (s *Status) SetChecks(val []Check) {
	s.Checks = val
}
