// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetHistory implements getHistory operation.
//
// Every configured check's recorded state over one window.
//
// GET /history
func (UnimplementedHandler) GetHistory(ctx context.Context, params GetHistoryParams) (r GetHistoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStatus implements getStatus operation.
//
// The whole estate's current status.
//
// GET /status
func (UnimplementedHandler) GetStatus(ctx context.Context) (r *Status, _ error) {
	return r, ht.ErrNotImplemented
}
