// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetHistory implements getHistory operation.
	//
	// Every configured check's recorded state over one window.
	//
	// GET /history
	GetHistory(ctx context.Context, params GetHistoryParams) (GetHistoryRes, error)
	// GetStatus implements getStatus operation.
	//
	// The whole estate's current status.
	//
	// GET /status
	GetStatus(ctx context.Context) (*Status, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
